# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 556d68abd0df506e4080b038a1321cbfbd31511d4142a29df778466ea9ce66a8cf7a15bf75dc6d361409f70caba40d9cb9710b457674404c252a8af955ca5e01

test:
  secret_key_base: 94602f4de433a53f937503c8c53ca5d7154a1c3535f82c386c1321f32572d645b41d04b89de439bcd4bb2fef4894662a944aa767e7feb7ee238af899e4cbd143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
